name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: Saionaro/extract-package-version@v1.0.6
        name: Extract version
        id: extract_version

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: deepacks/streakcloud-p-server
          tags: ${{ steps.extract_version.outputs.version }}, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
